spring.application.name=railwaycongestion
spring.datasource.url=jdbc:mysql://localhost:3306/railway_congestion
spring.datasource.username=root
spring.datasource.password=Manish1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
